[0m14:39:30.533218 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e2bd4d6b440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e2bd2e4a2d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e2bd2a3f0e0>]}


============================== 14:39:30.540108 | 56607361-24fc-410c-8012-17888944b7b4 ==============================
[0m14:39:30.540108 [info ] [MainThread]: Running with dbt=1.10.3
[0m14:39:30.541363 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/sam2/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init telegram_analytics', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:39:30.558095 [info ] [MainThread]: Creating dbt configuration folder at /home/sam2/.dbt
[0m14:39:30.562716 [debug] [MainThread]: Starter project path: /home/sam2/code/10x/Shipping-a-Data-Product-From-Raw-Telegram-Data-to-an-Analytical-API/venv/lib/python3.12/site-packages/dbt/include/starter_project
[0m14:39:30.571263 [info ] [MainThread]: 
Your new dbt project "telegram_analytics" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:39:30.572070 [info ] [MainThread]: Setting up your profile.
[0m14:39:30.574777 [error] [MainThread]: Encountered an error:

[0m14:39:30.577943 [error] [MainThread]: Traceback (most recent call last):
  File "/home/sam2/code/10x/Shipping-a-Data-Product-From-Raw-Telegram-Data-to-an-Analytical-API/venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 161, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam2/code/10x/Shipping-a-Data-Product-From-Raw-Telegram-Data-to-an-Analytical-API/venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 111, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam2/code/10x/Shipping-a-Data-Product-From-Raw-Telegram-Data-to-an-Analytical-API/venv/lib/python3.12/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
              ^^^^^^^^^^
  File "/home/sam2/code/10x/Shipping-a-Data-Product-From-Raw-Telegram-Data-to-an-Analytical-API/venv/lib/python3.12/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/home/sam2/code/10x/Shipping-a-Data-Product-From-Raw-Telegram-Data-to-an-Analytical-API/venv/lib/python3.12/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam2/code/10x/Shipping-a-Data-Product-From-Raw-Telegram-Data-to-an-Analytical-API/venv/lib/python3.12/site-packages/dbt/task/init.py", line 242, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam2/code/10x/Shipping-a-Data-Product-From-Raw-Telegram-Data-to-an-Analytical-API/venv/lib/python3.12/site-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/sam2/code/10x/Shipping-a-Data-Product-From-Raw-Telegram-Data-to-an-Analytical-API/venv/lib/python3.12/site-packages/click/termui.py", line 151, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m14:39:30.580990 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 0.13179636, "process_in_blocks": "14944", "process_kernel_time": 0.299694, "process_mem_max_rss": "99924", "process_out_blocks": "72", "process_user_time": 2.093877}
[0m14:39:30.581949 [debug] [MainThread]: Command `dbt init` failed at 14:39:30.581763 after 0.13 seconds
[0m14:39:30.582666 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e2bd239b7a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e2bd281e3c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7e2bd2049b80>]}
[0m14:39:30.583526 [debug] [MainThread]: Flushing usage events
[0m14:39:32.498602 [debug] [MainThread]: An error was encountered while trying to flush usage events
